POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "murillo@mail.com",
  "password": "Murill@1998"
}

# {
#   "email": "timclarkson@mail.com",
#   "password": "Timclarkson@123"
# }

###

POST http://localhost:3000/signup
Content-Type: application/json

{
  "name": "user9",
  "email": "user9@mail.com",
  "password": "User9p@ssword"
}

###

GET http://localhost:3000/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im11cmlsbG9AbWFpbC5jb20iLCJpYXQiOjE2OTgxMDA4NzMsImV4cCI6MTY5ODEyMjQ3M30.aBdRWzfSdP7FhRk_2Koxb4WCRQUMYUvFolKoV5FMHiE
